name: flutter_gemini
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.8.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^2.9.0
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1
  image_picker: ^1.2.0
  logger: ^2.6.1
  riverpod_annotation: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
